package utils;

public enum Properties {
	ADDRESS, ALIAS, CHECK_INTERVAL, CURRENT_STATE,
    EMAIL_NOTIF, HOSTNAME, LAST_CHECK, LAST_NOTIF, 
    MAX_CHECK_ATTEMPTS, NOTIF_INTERVAL, PORTS_LIST, RETRY_INTERVAL,
    TOLERANCE_ATTEMPTS
}
